version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  setup:
    build: .
    container_name: elasticsearch-setup
    depends_on:
      - elasticsearch
    entrypoint: ["python3", "/app/generate_fake_products.py"]
    volumes:
      - ./generate_fake_products.py:/app/generate_fake_products.py
      - ./data:/app/data  

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi-server
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
